version: '3'
services:
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/:/var/lib/mysql
    ports:
      - "3306:3306"

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    volumes: 
      - ./nextcloud/:/var/www/html/