---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Comprobar conexion a pagina de nextcloud
      ansible.builtin.uri:
        url: http://localhost/nextcloud/
      register: pagina


    - name: Comprobar codigo http
      ansible.builtin.assert:
        that: pagina.status == 200
        success_msg: "Web Nextcloud funcionando correctamente"
        fail_msg: "Web Nextcloud no esta funcionando correctamente"
